version: 1

formatters:
  brief:
    format: '%(message)s'
  default:
    format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class : logging.StreamHandler
    formatter: brief
    level   : DEBUG
    stream  : ext://sys.stdout
  root_log:
    class : logging.handlers.RotatingFileHandler
    formatter: default
    filename: log_root.log
    maxBytes: 1024
    backupCount: 3

root:
  level: WARNING
  handlers: [root_log]

loggers:

  # This logger is used to print the data being send through channels and ports
  channels_transmission:
    handlers: [console]
    level: WARNING

